name: reqcatcher
version: 0.1.0.1
synopsis: A local http server to catch the HTTP redirect
description: ! 'Manage an http server in your local PC to catch the HTTP

  redirect request from the browser. Especially, you can

  catch the redirect from oauth providor and will get

  oauth_verifier.'
category: Web
author: Masahiro Honma
maintainer: hiratara@cpan.org
license: BSD3
github: hiratara/hs-reqcatcher
homepage: http://github.com/hiratara/hs-reqcatcher
library:
  source-dirs: src
  exposed-modules:
  - Web.ReqCatcher
  dependencies:
  - base >=4.7 && <4.12
  - http-types >=0.8 && <1.0
  - network >=2.6 && <2.7
  - text >=1.2 && <1.3
  - wai >=3.0 && <3.3
  - warp >=3.0 && <3.3
tests:
  reqcatcher-test:
    main: reqcatcher-test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - http-client >=0.4 && <0.6
    - http-types
    - HUnit >=1.2 && <1.7
    - lens >=4.7 && <4.17
    - reqcatcher
    - tasty >=0.10 && <1.2
    - tasty-hunit >=0.9 && <1.0
    - wai
    - wreq >=0.3 && <0.6
